### ISSUE TITLE
[Feat] TVING 로그인 화면 작성

### ISSUE THREAD

**Issue by FpRaArNkK** [NOW-SOPT-iOS-Part/ParkMinSeo-assignment#1]
**Issue : Feature**
TVING 화면의 로그인 화면을 작성합니다.

**Description**
UI 작업을 먼저 진행한 후,
UI에 연결되는 이벤트들을 작성합니다.
초반 구조 + 에셋 추가 작업을 포함합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Color, Font, Image 추가
- [x] 로그인 화면 UI 작성
- [x] 로그인 화면 이벤트 작성
- [x] 웰컴 화면 UI 작성
- [x] 로그인-웰컴 화면 연결
- [x] 닉네임 바텀시트 화면 작성
- [x] 데이터 전달 추가

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
