### ISSUE TITLE
[Feat] TVING 홈 화면 작성

### ISSUE THREAD

**Issue by FpRaArNkK** [NOW-SOPT-iOS-Part/ParkMinSeo-assignment#3]
**Issue : Feature**
TVING 앱의 홈 화면을 작성합니다.

**Description**
데이터 연결 작업보다 UI 작성을 우선으로 작업합니다.
폴더링 + 에셋 추가 작업을 포함합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] AppTabBarController 작성
- [x] NormalContent Cell 작성
- [x] StreamContent Cell 작성
- [x] AdContent Cell 작성
- [x] HeaderView 작성
- [x] MainCollectionView - Compositional Layout 작성
- [x] HomeViewController 작성
- [x] SegmentControlCollectionViewController 작성

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
