### ISSUE TITLE
[Refactor] TVING 리팩토링

### ISSUE THREAD

**Issue by FpRaArNkK** [NOW-SOPT-iOS-Part/ParkMinSeo-assignment#7]
**Issue : Refactor**
TVING 메인 화면을 리팩토링합니다.

**Description**
TVING 메인 화면을 SOLID 원칙, MVVM 아키텍처, Reactive 프로그래밍, DI 등의 개념을 적용하여 리팩토링합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Reactive - RxSwift, RxCocoa 적용
- [x] MVC 구조 MVVM으로 리팩토링
- [ ] ViewModel 의존성 주입 작성
